---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

# build template
.build:
  stage: build
  image: docker:latest
  artifacts:
    expire_in: 1 day
    paths:
      - image
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

# test template
.test:
  stage: test
  image: docker:latest
  before_script:
    - docker load -i image/v0.10.0.tar
    - docker load -i image/v0.10.1.tar
    - docker load -i image/v0.10.2.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

# deploy template
.deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - docker load -i image/v0.10.0.tar
    - docker load -i image/v0.10.1.tar
    - docker load -i image/v0.10.2.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - test
  - deploy

# test
dockerlint:
  stage: lint
  image: vptech/linter:docker
  script:
    - find . -type f -name "Dockerfile" | xargs -I {} dockerlint {}

# build
v0.10.0:build:
  extends: .build
  script:
    - docker build --build-arg VERSION=0.10.0 --rm --tag nomad:0.10.0 .
    - mkdir image
    - docker save nomad:0.10.0 > image/v0.10.0.tar

v0.10.1:build:
  extends: .build
  script:
    - docker build --build-arg VERSION=0.10.1 --rm --tag nomad:0.10.1 .
    - mkdir image
    - docker save nomad:0.10.1 > image/v0.10.1.tar

v0.10.2:build:
  extends: .build
  script:
    - docker build --build-arg VERSION=0.10.2 --rm --tag nomad:0.10.2 .
    - mkdir image
    - docker save nomad:0.10.2 > image/v0.10.2.tar

# test
v0.10.0:test:
  extends: .test
  script:
    - docker run nomad:0.10.0 nomad -version

v0.10.1:test:
  extends: .test
  script:
    - docker run nomad:0.10.1 nomad -version

v0.10.2:test:
  extends: .test
  script:
    - docker run nomad:0.10.2 nomad -version

# deploy
# https://hub.docker.com/u/vpgrp/
# vpgrp:
#   extends: .deploy
#   script:
#     - docker tag nomad:0.10.0 vpgrp/nomad:0.10.0
#     - docker tag nomad:0.10.1 vpgrp/nomad:0.10.1
#     - docker tag nomad:0.10.2 vpgrp/nomad:0.10.2
#     - docker tag nomad:0.10.2 vpgrp/nomad:latest
#     - docker push vpgrp/nomad:0.10.0
#     - docker push vpgrp/nomad:0.10.1
#     - docker push vpgrp/nomad:0.10.2
#     - docker push vpgrp/nomad:latest

# https://hub.docker.com/u/vptech/
vptech:
  extends: .deploy
  script:
    - docker tag nomad:0.10.0 vptech/nomad:0.10.0
    - docker tag nomad:0.10.1 vptech/nomad:0.10.1
    - docker tag nomad:0.10.2 vptech/nomad:0.10.2
    - docker tag nomad:0.10.2 vptech/nomad:latest
    - docker push vptech/nomad:0.10.0
    - docker push vptech/nomad:0.10.1
    - docker push vptech/nomad:0.10.2
    - docker push vptech/nomad:latest
# EOF
