---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

# build template
.build:
  stage: build
  image: docker:latest
  artifacts:
    expire_in: 1 day
    paths:
      - image
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

# test template
.test:
  stage: test
  image: docker:latest
  before_script:
    - docker load -i image/v0.8.7.tar
    - docker load -i image/v0.9.0.tar
    - docker load -i image/v0.9.1.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

# deploy template
.deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - docker load -i image/v0.8.7.tar
    - docker load -i image/v0.9.0.tar
    - docker load -i image/v0.9.1.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - test
  - deploy

# test
dockerlint:
  stage: lint
  image: vptech/linter:docker
  script:
    - find . -type f -name "Dockerfile" | xargs -I {} dockerlint {}

# build
v0.8.7:build:
  extends: .build
  script:
    - docker build --rm --tag nomad:0.8.7 0.8.7
    - mkdir image
    - docker save nomad:0.8.7 > image/v0.8.7.tar

v0.9.0:build:
  extends: .build
  script:
    - docker build --rm --tag nomad:0.9.0 0.9.0
    - mkdir image
    - docker save nomad:0.9.0 > image/v0.9.0.tar

v0.9.1:build:
  extends: .build
  script:
    - docker build --rm --tag nomad:0.9.1 0.9.1
    - mkdir image
    - docker save nomad:0.9.1 > image/v0.9.1.tar

# test
v0.8.7:test:
  extends: .test
  script:
    - docker run nomad:0.8.7 "nomad -version"

v0.9.0:test:
  extends: .test
  script:
    - docker run nomad:0.9.0 "nomad -version"

v0.9.1:test:
  extends: .test
  script:
    - docker run nomad:0.9.1 "nomad -version"

# deploy
# https://hub.docker.com/u/vpgrp/
vpgrp:
  extends: .deploy
  script:
    - docker tag nomad:0.8.7 vpgrp/nomad:0.8.7
    - docker tag nomad:0.9.0 vpgrp/nomad:0.9.0
    - docker tag nomad:0.9.1 vpgrp/nomad:0.9.1
    - docker tag nomad:0.9.1 vpgrp/nomad:latest
    - docker push vpgrp/nomad:0.8.7
    - docker push vpgrp/nomad:0.9.0
    - docker push vpgrp/nomad:0.9.1
    - docker push vpgrp/nomad:latest

# https://hub.docker.com/u/vptech/
vptech:
  extends: .deploy
  script:
    - docker tag nomad:0.8.7 vptech/nomad:0.8.7
    - docker tag nomad:0.9.0 vptech/nomad:0.9.0
    - docker tag nomad:0.9.1 vptech/nomad:0.9.1
    - docker tag nomad:0.9.1 vptech/nomad:latest
    - docker push vptech/nomad:0.8.7
    - docker push vptech/nomad:0.9.0
    - docker push vptech/nomad:0.9.1
    - docker push vptech/nomad:latest
# EOF
