---

include:
  - project: veepee/vptech/sre/iac/ci-cd/docker-build
    ref: 4.3.3
    file: gitlab-ci-build.yml
  - project: veepee/vptech/sre/iac/ci-cd/docker-lint
    ref: 2.0.2
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.2.2
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.2.1
    file: gitlab-ci.yml

variables:
  APP_NAME: nomad
  SEMANTIC_CONFIG_FILE: changelog
  DOCKER_PUBLIC_REGISTRY_URL: docker.io
  DOCKER_PUBLIC_REGISTRY_USERNAME: ${PUBLIC_REGISTRY_USERNAME}
  DOCKER_PUBLIC_REGISTRY_PASSWORD: ${PUBLIC_REGISTRY_PASSWORD}
  DOCKER_PUBLIC_REPO: vptech
  PUBLIC: 'true'

stages:
  - lint
  - build
  - test
  - publish
  - release

publish-feature:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg NOMAD_VERSION=${VERSION}
    TAG: "${CI_COMMIT_REF_SLUG}-${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '0.11.8', '0.12.9' ]

delete-feature:docker:
  variables:
    TAG: '${CI_COMMIT_REF_SLUG}-0.11.8 ${CI_COMMIT_REF_SLUG}-0.12.9'

publish-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg NOMAD_VERSION=${VERSION}
    TAG: "${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '0.11.8', '0.12.9' ]

publish-public-release:docker:
  variables:
    DOCKER_BUILD_ARGS: --build-arg NOMAD_VERSION=${VERSION}
    TAG: "${VERSION}"
  parallel:
    matrix:
      - NAME: [ 'VERSION' ]
        VERSION: [ '0.11.8', '0.12.9' ]
...
