---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

# build template
.build:
  stage: build
  image: docker:latest
  artifacts:
    expire_in: 1 day
    paths:
      - image
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

# test template
.test:
  stage: test
  image: docker:latest
  before_script:
    - docker load -i image/v0.9.4.tar
    - docker load -i image/v0.9.5.tar
    - docker load -i image/v0.9.6.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

# deploy template
.deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - docker load -i image/v0.9.4.tar
    - docker load -i image/v0.9.5.tar
    - docker load -i image/v0.9.6.tar
  only:
    - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - test
  - deploy

# test
dockerlint:
  stage: lint
  image: vptech/linter:docker
  script:
    - find . -type f -name "Dockerfile" | xargs -I {} dockerlint {}

# build
v0.9.4:build:
  extends: .build
  script:
    - docker build --rm --tag nomad:0.9.4 0.9.4
    - mkdir image
    - docker save nomad:0.9.4 > image/v0.9.4.tar

v0.9.5:build:
  extends: .build
  script:
    - docker build --rm --tag nomad:0.9.5 0.9.5
    - mkdir image
    - docker save nomad:0.9.5 > image/v0.9.5.tar

v0.9.6:build:
  extends: .build
  script:
    - docker build --rm --tag nomad:0.9.6 0.9.6
    - mkdir image
    - docker save nomad:0.9.6 > image/v0.9.6.tar

# test
v0.9.4:test:
  extends: .test
  script:
    - docker run nomad:0.9.4 nomad -version

v0.9.5:test:
  extends: .test
  script:
    - docker run nomad:0.9.5 nomad -version

v0.9.6:test:
  extends: .test
  script:
    - docker run nomad:0.9.6 nomad -version

# deploy
# https://hub.docker.com/u/vpgrp/
vpgrp:
  extends: .deploy
  script:
    - docker tag nomad:0.9.4 vpgrp/nomad:0.9.4
    - docker tag nomad:0.9.5 vpgrp/nomad:0.9.5
    - docker tag nomad:0.9.6 vpgrp/nomad:0.9.6
    - docker tag nomad:0.9.6 vpgrp/nomad:latest
    - docker push vpgrp/nomad:0.9.4
    - docker push vpgrp/nomad:0.9.5
    - docker push vpgrp/nomad:0.9.6
    - docker push vpgrp/nomad:latest

# https://hub.docker.com/u/vptech/
vptech:
  extends: .deploy
  script:
    - docker tag nomad:0.9.4 vptech/nomad:0.9.4
    - docker tag nomad:0.9.5 vptech/nomad:0.9.5
    - docker tag nomad:0.9.6 vptech/nomad:0.9.6
    - docker tag nomad:0.9.6 vptech/nomad:latest
    - docker push vptech/nomad:0.9.4
    - docker push vptech/nomad:0.9.5
    - docker push vptech/nomad:0.9.6
    - docker push vptech/nomad:latest
# EOF
